#! /bin/sh

name=ktest-init
version=1.0
revision=1

hostdeps="gcc"
imagedeps="build-essential"

source_dir=ktest-init
deps="mlibc libgcc"

build() {
    echo ${sysroot_dir}
    ${TARGET_CC} -v -static ${source_dir}/main.c -o init
}

package() {
    mkdir -p ${dest_dir}/sbin
    install init ${dest_dir}/sbin/init
}
