#! /bin/sh

name=ktest-init
version=1.0
revision=1

hostdeps="gcc"
imagedeps="build-essential"

source_dir=ktest-init
deps="mlibc libgcc"

build() {
    find /sysroot/usr/lib -type f
    ${TARGET_CC} -static -v -g ${source_dir}/main.c -o init
}

package() {
    mkdir -p ${dest_dir}/sbin
    install init ${dest_dir}/sbin/init
}
