#! /bin/sh

name=meow
version=1.0
revision=1

hostdeps="gcc"
imagedeps="build-essential"

source_dir=meow
deps="mlibc libgcc"

build() {
    ${TARGET_CC} ${source_dir}/meow.c -o meow
}

package() {
    mkdir -p ${dest_dir}/usr/bin
    install meow ${dest_dir}/usr/bin/meow
}
