#!/bin/sh

name=mlibc-headers
revision=1

imagedeps="meson ninja-build"
hostdeps="pkg-config"

from_source=mlibc

configure() {
    meson_configure \
        -Dheaders_only=true
}

build() {
    ninja -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" ninja install
}
