#! /bin/sh

name=readline
_patch=01
version=8.3p${_patch}
revision=1
tarball_url="https://ftpmirror.gnu.org/gnu/readline/readline-8.3.tar.gz"
tarball_blake2b="45d6fe7e34c56d309102a94aa776a7f5284201e844450e14ff818df9fa84a72154bdca70f11828c94954b080cbbe4666fa0b00ffa8460118ec8f3ea551b73dad"
source_allow_network="yes"
hostdeps="gcc pkg-config"
deps="core-libs ncurses"

prepare() {
    for p in $(seq -w 0${_patch}); do
        curl -L https://ftpmirror.gnu.org/gnu/readline/readline-8.3-patches/readline83-$p | patch -p0
    done

    autotools_recursive_regen
}

configure() {
    autotools_configure \
        --enable-multibyte \
        --with-curses
}

build() {
    make SHLIB_LIBS="-lncursesw -ltinfow" -j${parallelism}
}

package() {
    make install DESTDIR="${dest_dir}"

    ln -svn libhistory.so.8.3 ${dest_dir}${prefix}/lib/libhistory.so.8
    ln -svn libreadline.so.8.3 ${dest_dir}${prefix}/lib/libreadline.so.8
    ln -svn libhistory.so.8 ${dest_dir}${prefix}/lib/libhistory.so
    ln -svn libreadline.so.8 ${dest_dir}${prefix}/lib/libreadline.so
}
