#! /bin/sh

JINX_MAJOR_VER=0.8
JINX_ARCH=riscv64
TARGET_TRIPLET=${JINX_ARCH}-unknown-badgeros-mlibc

JINX_DEBIAN_SNAPSHOT=20251202T083052Z
JINX_BASE_PACKAGES="gettext-base build-essential"

HOST_CFLAGS="-O2"
HOST_CXXFLAGS="${HOST_CFLAGS}"
HOST_LDFLAGS="-Wl,--as-needed -Wl,-z,now"

TARGET_CFLAGS="$HOST_CFLAGS"
TARGET_CXXFLAGS="$HOST_CXXFLAGS"
TARGET_LDFLAGS="$HOST_LDFLAGS"

TARGET_CC="${TARGET_TRIPLET}-gcc"
TARGET_CXX="${TARGET_TRIPLET}-g++"

case ${JINX_ARCH} in
    riscv64 )
        TARGET_CFLAGS="${TARGET_CFLAGS} -march=rv64gc -mabi=lp64d -static"
        TARGET_CXXFLAGS="${TARGET_CXXFLAGS} -march=rv64gc -mabi=lp64d -static"
        ;;
    * )
        echo "UNKNOWN ARCHITECTURE!"
        echo "Don't know how to build BadgerOS for ${JINX_ARCH}"
        exit 1
        ;;
esac

meson_configure() {
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    meson_configure_noflags "$@"
}

meson_configure_noflags() {
    if [ -z "${meson_source_dir}" ]; then
        meson_source_dir="${source_dir}"
    fi

        JINX_ARCH=${JINX_ARCH} \
        TARGET_TRIPLET=${TARGET_TRIPLET} \
        sysroot_dir=${sysroot_dir} \
    envsubst < "${base_dir}/misc/meson-cross.conf" > ./cross-file.txt

    meson setup "${meson_source_dir}" \
        --cross-file=cross-file.txt \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --libdir=lib \
        --sbindir=sbin \
        --bindir=bin \
        --datadir=share \
        --buildtype=release \
        -Ddefault_library=shared \
        "$@"
}

checked_subst() {
    tmpfile="$2".checked_subst
    sed -z -E -e "$1" "$2" >"$tmpfile"
    if cmp -s "$2" "$tmpfile"; then
        rm -f "$2".checked_subst
        if [ "$3" = no_die ]; then
            return 1
        else
            die "*** substitution '$1' failed for file '$2'"
        fi
    fi

    #diff --color=auto -ur "$2" "$tmpfile" || true

    touch -r "$2" "$2".checked_subst
    chmod --reference="$2" "$2".checked_subst
    mv -f "$2".checked_subst "$2"
}

autotools_recursive_regen() {
    for f in $(grep -rl 'GNU config.sub ($timestamp)'); do
        mv "$f" "$f".reference
        cp -v ${base_dir}/misc/config.sub "$f"
        touch -r "$f".reference "$f"
        rm -f "$f".reference
    done
    for f in $(grep -rl 'GNU config.guess ($timestamp)'); do
        mv "$f" "$f".reference
        cp -v ${base_dir}/misc/config.guess "$f"
        touch -r "$f".reference "$f"
        rm -f "$f".reference
    done

    if ! [ -z "$(grep -rl "# No shared lib support for Linux oldld, aout, or coff.")" ]; then
        if [ -z "$(grep -rl "dynamic_linker='mlibc ld.so'")" ]; then
            echo "*** Missing libtool support for mlibc - trying to patch support in :3 ***"
            for f in $(grep -rl "We cannot seem to hardcode it, guess we'll fake it."); do
                if grep -q 'add_dir="\?-L$lt_sysroot$libdir"\?' "$f"; then
                    continue
                fi
                checked_subst 's/add_dir=(")?-L\$libdir(")?/add_dir=\1-L$lt_sysroot$libdir\1/g' "$f"
            done
            for f in $(grep -rl "# No shared lib support for Linux oldld, aout, or coff."); do
                if grep -q 'AC_DEFUN(\[AC_PROG_LIBTOOL\]' "$f"; then
                    continue
                fi
                if grep -q 'ltconfig - Create a system-specific libtool' "$f"; then
                    continue
                fi
                checked_subst 's/(# This must be (glibc\/|Linux )?ELF.\nlinux\* \| k\*bsd\*-gnu \| kopensolaris\*-gnu( \| gnu\*)?( \| uclinuxfdpiceabi)?)(\)\n  lt_cv_deplibs_check_method=pass_all)/\1 | *-mlibc\5/g' "$f"
                checked_subst 's/(\)\n	# FreeBSD uses GNU C)/ | *-mlibc\1/g' "$f" no_die || true
                checked_subst 's/(lt_prog_compiler_static(_[^=]*)?='"'"'-non_shared'"'"'\n      ;;)(\n\n    linux\* \| k\*bsd\*-gnu \| kopensolaris\*-gnu( \| gnu\*)?\))/\1\n\n    *-mlibc)\n      lt_prog_compiler_wl\2='"'"'-Wl,'"'"'\n      lt_prog_compiler_pic\2='"'"'-fPIC'"'"'\n      lt_prog_compiler_static\2='"'"'-static'"'"'\n      ;;\3/g' "$f"
                checked_subst 's/(    (haiku|interix\[3-9\])?\*\)\n      (archive_cmds|hardcode_direct)?(_[^=]*)?=)/    *-mlibc)\n      archive_cmds\4='"'"'$CC -shared $pic_flag $libobjs $deplibs $compiler_flags $wl-soname $wl$soname -o $lib'"'"'\n      archive_expsym_cmds\4='"'"'$CC -shared $pic_flag $libobjs $deplibs $compiler_flags $wl-soname $wl$soname $wl-retain-symbols-file $wl$export_symbols -o $lib'"'"'\n      ;;\n\n\1/g' "$f"
                checked_subst 's/(\)\n        # FreeBSD 3 and later use GNU C)/ | *-mlibc\1/g' "$f" no_die || true
                # putting this last to avoid a bug with determining whether the substitutions should be run or not.
                checked_subst 's/(hardcode_into_libs=yes\n  ;;\n\n)(# No shared lib support for Linux oldld, aout, or coff.)/\1*-mlibc)\n  version_type=linux\n  need_lib_prefix=no\n  need_version=no\n  library_names_spec='"'"'$libname$release$shared_ext$versuffix $libname$release$shared_ext$major $libname$shared_ext'"'"'\n  soname_spec='"'"'$libname$release$shared_ext$major'"'"'\n  dynamic_linker='"'"'mlibc ld.so'"'"'\n  shlibpath_var=LD_LIBRARY_PATH\n  shlibpath_overrides_runpath=no\n  hardcode_into_libs=yes\n  ;;\n\n\2/g' "$f"
            done
        fi
    fi
}

autotools_configure() {
        CC="$TARGET_CC" \
        CXX="$TARGET_CXX" \
        CFLAGS="$TARGET_CFLAGS" \
        CXXFLAGS="$TARGET_CXXFLAGS" \
        LDFLAGS="$TARGET_LDFLAGS" \
    autotools_configure_noflags "$@"
}

autotools_configure_noflags() {
    if [ -z "${configure_script_path}" ]; then
        configure_script_path="${source_dir}/configure"
    fi

        ac_cv_func_malloc_0_nonnull=yes \
        ac_cv_func_calloc_0_nonnull=yes \
        ac_cv_func_realloc_0_nonnull=yes \
    ${configure_script_path} \
        --host=${TARGET_TRIPLET} \
        --with-sysroot=${sysroot_dir} \
        --prefix=${prefix} \
        --sysconfdir=/etc \
        --localstatedir=/var \
        --bindir=${prefix}/bin \
        --sbindir=${prefix}/bin \
        --libdir=${prefix}/lib \
        --enable-static \
        --disable-shared \
        --disable-malloc0returnsnull \
        "$@"
}
