[package]
name = "badgeros_kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
test = false

[dependencies]
bytemuck = "1.23.0"
tock-registers = "0.9.0"

[build-dependencies]
bindgen = "0.71.0"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
