[package]
name = "badgeros_kernel"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]
test = false

[dependencies]

[build-dependencies]
bindgen = "0.71.0"

[profile.dev]
panic = "abort"
[profile.release]
panic = "abort"
